Update README.md - cmake is required for make release
On m1 Mac running `make release` fails on first attempt if user does not have `cmake` installed.

```
error: failed to run custom build command for `snmalloc-sys v0.3.4`
```